// frontend-vue/src/views/EditLink.vue
<template>
  <div class="container">
    <h1>Edit Link</h1>
    <div v-if="loading" class="loading">Loading...</div>
    <div v-else-if="error" class="error">{{ error }}</div>
    <form v-else @submit.prevent="handleSubmit">
      <div class="form-group">
        <label for="title">Title:</label>
        <input type="text" id="title" v-model="formData.title" required />
      </div>

      <div class="form-group">
        <label for="url">URL:</label>
        <input type="url" id="url" v-model="formData.url" required />
      </div>

      <div class="form-group">
        <label for="description">Description:</label>
        <textarea id="description" rows="4" v-model="formData.description"></textarea>
      </div>

      <div class="form-group">
        <label for="tags">Tags (comma-separated):</label>
        <input type="text" id="tags" v-model="formData.tags" />
      </div>

      <div class="form-group text-center">
        <button type="submit" class="mb-20">Update Link</button>
        <router-link to="/">
          <button type="button" class="delete">Cancel</button>
        </router-link>
      </div>
    </form>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { api } from '../services/api'

const router = useRouter()
const route = useRoute()

const formData = ref({
  title: '',
  url: '',
  description: '',
  tags: '',
})
const loading = ref(true)
const error = ref(null)

const loadLink = async () => {
  try {
    const response = await api.getLink(route.params.id)
    const link = response.data
    formData.value = {
      title: link.title,
      url: link.url,
      description: link.description || '',
      tags: link.tags ? link.tags.join(', ') : '',
    }
  } catch (err) {
    error.value = 'Error loading link'
    console.error('Error loading link:', err)
  } finally {
    loading.value = false
  }
}

const handleSubmit = async () => {
  try {
    await api.updateLink(route.params.id, {
      ...formData.value,
      tags: formData.value.tags
        .split(',')
        .map((tag) => tag.trim())
        .filter((tag) => tag),
    })
    router.push('/')
  } catch (err) {
    console.error('Error updating link:', err)
    alert('Error updating link')
  }
}

onMounted(() => {
  loadLink()
})
</script>

// frontend-angular/src/app/components/edit-link/edit-link.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule, Router, ActivatedRoute } from '@angular/router';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-edit-link',
  templateUrl: './edit-link.component.html',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
})
export class EditLinkComponent implements OnInit {
  formData = {
    title: '',
    url: '',
    description: '',
    tags: '',
  };
  loading = true;
  error: string | null = null;
  private id: string | null = null;

  constructor(
    private api: ApiService,
    private route: ActivatedRoute,
    private router: Router
  ) {}

  ngOnInit() {
    this.id = this.route.snapshot.paramMap.get('id');
    if (this.id) {
      this.loadLink(this.id);
    }
  }

  async loadLink(id: string) {
    try {
      this.loading = true;
      const response = await this.api.getLink(id);
      const link = response.data;
      this.formData = {
        title: link.title,
        url: link.url,
        description: link.description || '',
        tags: link.tags ? link.tags.join(', ') : '',
      };
    } catch (err) {
      this.error = 'Error loading link';
      console.error('Error loading link:', err);
    } finally {
      this.loading = false;
    }
  }

  async handleSubmit() {
    if (!this.id) return;

    try {
      await this.api.updateLink(this.id, {
        ...this.formData,
        tags: this.formData.tags
          .split(',')
          .map((tag) => tag.trim())
          .filter((tag) => tag),
      });
      this.router.navigate(['/']);
    } catch (err) {
      console.error('Error updating link:', err);
      alert('Error updating link');
    }
  }
}

<div class="container">
  <h1>Edit Link</h1>
  <ng-container *ngIf="loading">
    <div class="loading">Loading...</div>
  </ng-container>

  <ng-container *ngIf="error">
    <div class="error">{{ error }}</div>
  </ng-container>

  <ng-container *ngIf="!loading && !error">
    <form (ngSubmit)="handleSubmit()">
      <div class="form-group">
        <label for="title">Title:</label>
        <input
          type="text"
          id="title"
          [(ngModel)]="formData.title"
          name="title"
          required
        />
      </div>

      <div class="form-group">
        <label for="url">URL:</label>
        <input
          type="url"
          id="url"
          [(ngModel)]="formData.url"
          name="url"
          required
        />
      </div>

      <div class="form-group">
        <label for="description">Description:</label>
        <textarea
          id="description"
          rows="4"
          [(ngModel)]="formData.description"
          name="description"
        ></textarea>
      </div>

      <div class="form-group">
        <label for="tags">Tags (comma-separated):</label>
        <input type="text" id="tags" [(ngModel)]="formData.tags" name="tags" />
      </div>

      <div class="form-group text-center">
        <button type="submit" class="mb-20">Update Link</button>
        <a routerLink="/">
          <button type="button" class="delete">Cancel</button>
        </a>
      </div>
    </form>
  </ng-container>
</div>
