// frontend-svelte/src/App.svelte
<script>
  import { Router, Link, Route } from "svelte-routing";
  import LinkList from "./routes/LinkList.svelte";
  import LinkDetail from "./routes/LinkDetail.svelte";
  import CreateLink from "./routes/CreateLink.svelte";
  import EditLink from "./routes/EditLink.svelte";
  
  export let url = "";
</script>

<Router {url}>
  <nav>
    <Link to="/">Home</Link>
  </nav>

  <main>
    <Route path="/" component={LinkList} />
    <Route path="/link/:id" let:params>
      <LinkDetail id={params.id} />
    </Route>
    <Route path="/create" component={CreateLink} />
    <Route path="/edit/:id" component={EditLink} />
  </main>
</Router>

// frontend-react/src/App.js
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import LinkList from "./components/LinkList";
import LinkDetail from "./components/LinkDetail";
import CreateLink from "./components/CreateLink";
import EditLink from "./components/EditLink";
import "./styles/global.css";

function App() {
  return (
    <Router>
      <div className="container">
        <Routes>
          <Route path="/" element={<LinkList />} />
          <Route path="/link/:id" element={<LinkDetail />} />
          <Route path="/create" element={<CreateLink />} />
          <Route path="/edit/:id" element={<EditLink />} />
        </Routes>
      </div>
    </Router>
  );
}

export default App;
