// frontend-react/src/components/CreateLink.jsx
import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { api } from "../services/api";

function CreateLink() {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    title: "",
    url: "",
    description: "",
    tags: "",
  });

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      await api.createLink({
        ...formData,
        tags: formData.tags
          .split(",")
          .map((tag) => tag.trim())
          .filter((tag) => tag),
      });
      navigate("/");
    } catch (error) {
      console.error("Error creating link:", error);
      alert("Error creating link");
    }
  };

  return (
    <div className="container">
      <h1>Create New Link</h1>
      <form onSubmit={handleSubmit}>
        <div className="form-group">
          <label htmlFor="title">Title:</label>
          <input
            type="text"
            id="title"
            name="title"
            value={formData.title}
            onChange={handleChange}
            required
          />
        </div>

        <div className="form-group">
          <label htmlFor="url">URL:</label>
          <input
            type="url"
            id="url"
            name="url"
            value={formData.url}
            onChange={handleChange}
            required
          />
        </div>

        <div className="form-group">
          <label htmlFor="description">Description:</label>
          <textarea
            id="description"
            name="description"
            rows="4"
            value={formData.description}
            onChange={handleChange}
          />
        </div>

        <div className="form-group">
          <label htmlFor="tags">Tags (comma-separated):</label>
          <input
            type="text"
            id="tags"
            name="tags"
            value={formData.tags}
            onChange={handleChange}
          />
        </div>

        <div className="form-group text-center">
          <button type="submit" className="mb-20">
            Create Link
          </button>
          <Link to="/">
            <button type="button" className="delete">
              Cancel
            </button>
          </Link>
        </div>
      </form>
    </div>
  );
}

export default CreateLink;

// frontend-svelte/src/routes/CreateLink.svelte
<script>
  import { navigate } from 'svelte-routing';
  import { Link } from 'svelte-routing';
  import { api } from '../lib/api';

  let formData = {
    title: '',
    url: '',
    description: '',
    tags: ''
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    try {
      await api.createLink({
        ...formData,
        tags: formData.tags
          .split(',')
          .map(tag => tag.trim())
          .filter(tag => tag)
      });
      navigate('/');
    } catch (err) {
      console.error('Error creating link:', err);
      alert('Error creating link');
    }
  };
</script>

<div class="container">
  <h1>Create New Link</h1>
  <form on:submit={handleSubmit}>
    <div class="form-group">
      <label for="title">Title:</label>
      <input
        type="text"
        id="title"
        bind:value={formData.title}
        required
      />
    </div>

    <div class="form-group">
      <label for="url">URL:</label>
      <input
        type="url"
        id="url"
        bind:value={formData.url}
        required
      />
    </div>

    <div class="form-group">
      <label for="description">Description:</label>
      <textarea
        id="description"
        rows="4"
        bind:value={formData.description}
      ></textarea>
    </div>

    <div class="form-group">
      <label for="tags">Tags (comma-separated):</label>
      <input
        type="text"
        id="tags"
        bind:value={formData.tags}
      />
    </div>

    <div class="form-group text-center">
      <button type="submit" class="mb-20">Create Link</button>
      <Link to="/">
        <button type="button" class="delete">Cancel</button>
      </Link>
    </div>
  </form>
</div>
