// frontend-react/src/components/LinkDetail.jsx
import { useState, useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import { api } from "../services/api";

function LinkDetail() {
  const { id } = useParams();
  const [link, setLink] = useState(null);
  const [comments, setComments] = useState([]);
  const [newComment, setNewComment] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    loadLinkAndComments();
  }, [id]);

  const loadLinkAndComments = async () => {
    try {
      setLoading(true);
      const [linkResponse, commentsResponse] = await Promise.all([
        api.getLink(id),
        api.getComments(id),
      ]);
      setLink(linkResponse.data);
      setComments(commentsResponse.data);
    } catch (error) {
      setError("Error loading link details");
      console.error("Error:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleVote = async (value) => {
    try {
      const response = await api.voteLink(id, value);
      setLink(response.data);
    } catch (error) {
      console.error("Error voting:", error);
      alert("Error voting");
    }
  };

  const handleCommentSubmit = async (e) => {
    e.preventDefault();
    if (!newComment.trim()) return;

    try {
      await api.createComment({
        linkId: id,
        content: newComment,
      });
      setNewComment("");
      const commentsResponse = await api.getComments(id);
      setComments(commentsResponse.data);
    } catch (error) {
      console.error("Error posting comment:", error);
      alert("Error posting comment");
    }
  };

  if (loading) return <div className="loading">Loading...</div>;
  if (error) return <div className="error">{error}</div>;
  if (!link) return <div className="error">Link not found</div>;

  return (
    <div className="container">
      <div className="text-center mb-20">
        <Link to="/">
          <button>Back to List</button>
        </Link>
      </div>

      <div className="link-card">
        <h2>{link.title}</h2>
        <p>
          <a href={link.url} target="_blank" rel="noopener noreferrer">
            {link.url}
          </a>
        </p>
        <p className="description">{link.description}</p>
        <div className="tags">
          {link.tags?.map((tag) => (
            <span key={tag} className="tag-filter">
              {tag}
            </span>
          ))}
        </div>
      </div>

      <div className="votes">
        <h3>Votes: {link.votes}</h3>
        <div className="vote-buttons">
          <button onClick={() => handleVote(1)}>👍 Upvote</button>
          <button onClick={() => handleVote(-1)} className="delete">
            👎 Downvote
          </button>
        </div>
      </div>

      <div className="comments">
        <h3>Comments</h3>
        <form onSubmit={handleCommentSubmit} className="comment-form">
          <div className="form-group">
            <textarea
              value={newComment}
              onChange={(e) => setNewComment(e.target.value)}
              rows="4"
              placeholder="Write your comment here..."
              required
            />
          </div>
          <div className="text-center">
            <button type="submit">Add Comment</button>
          </div>
        </form>

        <div className="comments-list mt-20">
          {comments.map((comment) => (
            <div key={comment._id} className="comment">
              <p>{comment.content}</p>
              <small>{new Date(comment.createdAt).toLocaleString()}</small>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default LinkDetail;

// frontend-vue/src/views/LinkDetail.vue
<template>
  <div class="container">
    <div class="text-center mb-20">
      <router-link to="/">
        <button>Back to List</button>
      </router-link>
    </div>

    <div v-if="loading" class="loading">Loading...</div>
    <div v-else-if="error" class="error">{{ error }}</div>
    <template v-else-if="link">
      <div class="link-card">
        <h2>{{ link.title }}</h2>
        <p>
          <a :href="link.url" target="_blank">{{ link.url }}</a>
        </p>
        <p class="description">{{ link.description }}</p>
        <div class="tags">
          <span v-for="tag in link.tags" :key="tag" class="tag-filter">
            {{ tag }}
          </span>
        </div>
      </div>

      <div class="votes">
        <h3>Votes: {{ link.votes }}</h3>
        <div class="vote-buttons">
          <button @click="handleVote(1)">👍 Upvote</button>
          <button class="delete" @click="handleVote(-1)">👎 Downvote</button>
        </div>
      </div>

      <div class="comments">
        <h3>Comments</h3>
        <form @submit.prevent="handleCommentSubmit" class="comment-form">
          <div class="form-group">
            <textarea
              v-model="newComment"
              rows="4"
              placeholder="Write your comment here..."
              required
            ></textarea>
          </div>
          <div class="text-center">
            <button type="submit">Add Comment</button>
          </div>
        </form>

        <div class="comments-list mt-20">
          <div v-for="comment in comments" :key="comment._id" class="comment">
            <p>{{ comment.content }}</p>
            <small>{{ new Date(comment.createdAt).toLocaleString() }}</small>
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { api } from '../services/api'

const route = useRoute()
const link = ref(null)
const comments = ref([])
const newComment = ref('')
const loading = ref(true)
const error = ref(null)

const loadLinkAndComments = async () => {
  try {
    loading.value = true
    const [linkResponse, commentsResponse] = await Promise.all([
      api.getLink(route.params.id),
      api.getComments(route.params.id),
    ])
    link.value = linkResponse.data
    comments.value = commentsResponse.data
  } catch (err) {
    error.value = 'Error loading link details'
    console.error('Error:', err)
  } finally {
    loading.value = false
  }
}

const handleVote = async (value) => {
  try {
    const response = await api.voteLink(route.params.id, value)
    link.value = response.data
  } catch (err) {
    console.error('Error voting:', err)
    alert('Error voting')
  }
}

const handleCommentSubmit = async () => {
  if (!newComment.value.trim()) return

  try {
    await api.createComment({
      linkId: route.params.id,
      content: newComment.value,
    })
    newComment.value = ''
    const commentsResponse = await api.getComments(route.params.id)
    comments.value = commentsResponse.data
  } catch (err) {
    console.error('Error posting comment:', err)
    alert('Error posting comment')
  }
}

onMounted(() => {
  loadLinkAndComments()
})
</script>
