// frontend-angular/src/app/components/link-list/link-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { Link } from '../../models/link.interface';

@Component({
  selector: 'app-link-list',
  templateUrl: './link-list.component.html',
  standalone: true,
  imports: [CommonModule, RouterModule],
})
export class LinkListComponent implements OnInit {
  links: Link[] = [];
  activeTags: Set<string> = new Set();
  allTags: string[] = [];
  loading = true;
  error: string | null = null;

  constructor(private api: ApiService) {}

  ngOnInit() {
    this.loadLinks();
  }

  async loadLinks() {
    try {
      this.loading = true;
      const response = await this.api.getAllLinks();
      this.links = response.data;
      this.updateTags(response.data);
    } catch (err) {
      this.error = 'Error loading links';
      console.error('Error loading links:', err);
    } finally {
      this.loading = false;
    }
  }

  updateTags(links: Link[]) {
    const tagSet = new Set<string>();
    links.forEach((link) => {
      if (link.tags) {
        link.tags.forEach((tag) => tagSet.add(tag));
      }
    });
    this.allTags = Array.from(tagSet).sort();
  }

  toggleTag(tag: string) {
    if (this.activeTags.has(tag)) {
      this.activeTags.delete(tag);
    } else {
      this.activeTags.add(tag);
    }
  }

  clearTags() {
    this.activeTags.clear();
  }

  get filteredLinks() {
    return this.links.filter((link) => {
      if (this.activeTags.size === 0) return true;
      return (
        link.tags &&
        Array.from(this.activeTags).every((tag) => link.tags!.includes(tag))
      );
    });
  }

  async deleteLink(id: string) {
    if (!confirm('Are you sure you want to delete this link?')) return;

    try {
      await this.api.deleteLink(id);
      await this.loadLinks();
    } catch (err) {
      console.error('Error deleting link:', err);
      alert('Error deleting link');
    }
  }
}

<div class="container">
  <h1>Link Library</h1>
  <div class="text-center mb-20">
    <a routerLink="/create">
      <button>Create New Link</button>
    </a>
  </div>

  <ng-container *ngIf="loading">
    <div class="loading">Loading links...</div>
  </ng-container>

  <ng-container *ngIf="error">
    <div class="error">{{ error }}</div>
  </ng-container>

  <ng-container *ngIf="!loading && !error">
    <div class="filter-section">
      <h3>Filter by Tags:</h3>
      <div class="tag-filters">
        <button
          *ngFor="let tag of allTags"
          class="tag-filter"
          [class.active]="activeTags.has(tag)"
          (click)="toggleTag(tag)"
        >
          {{ tag }}
        </button>
      </div>
      <button *ngIf="activeTags.size > 0" (click)="clearTags()">
        Clear Filters
      </button>
    </div>

    <div class="links">
      <p *ngIf="filteredLinks.length === 0" class="text-center">
        No links available.
      </p>

      <div *ngFor="let link of filteredLinks" class="link-card">
        <h3>
          <a [href]="link.url" target="_blank" rel="noopener noreferrer">
            {{ link.title }}
          </a>
        </h3>
        <div class="tags">
          <span *ngFor="let tag of link.tags" class="tag-filter">
            {{ tag }}
          </span>
        </div>
        <p class="description">{{ link.description }}</p>
        <div class="actions">
          <a [routerLink]="['/link', link._id]">
            <button>View</button>
          </a>
          <a [routerLink]="['/edit', link._id]">
            <button>Edit</button>
          </a>
          <button class="delete" (click)="deleteLink(link._id)">Delete</button>
        </div>
      </div>
    </div>
  </ng-container>
</div>

// frontend-vue/src/views/LinkList.vue
<template>
  <div class="container">
    <h1>Link Library</h1>
    <div class="text-center mb-20">
      <router-link to="/create">
        <button>Create New Link</button>
      </router-link>
    </div>

    <div v-if="loading" class="loading">Loading links...</div>
    <div v-else-if="error" class="error">{{ error }}</div>
    <template v-else>
      <div class="filter-section">
        <h3>Filter by Tags:</h3>
        <div class="tag-filters">
          <span
            v-for="tag in allTags"
            :key="tag"
            class="tag-filter"
            :class="{ active: activeTags.has(tag) }"
            @click="toggleTag(tag)"
          >
            {{ tag }}
          </span>
        </div>
        <button v-if="activeTags.size" @click="clearTags">Clear Filters</button>
      </div>

      <div class="links">
        <div v-if="filteredLinks.length === 0" class="text-center">No links available.</div>
        <div v-else v-for="link in filteredLinks" :key="link._id" class="link-card">
          <h3>
            <a :href="link.url" target="_blank">{{ link.title }}</a>
          </h3>
          <div class="tags">
            <span v-for="tag in link.tags" :key="tag" class="tag-filter">
              {{ tag }}
            </span>
          </div>
          <p class="description">{{ link.description }}</p>
          <div class="actions">
            <router-link :to="`/link/${link._id}`">
              <button>View</button>
            </router-link>
            <router-link :to="`/edit/${link._id}`">
              <button>Edit</button>
            </router-link>
            <button class="delete" @click="deleteLink(link._id)">Delete</button>
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

<script setup>
import { ref, onMounted, computed } from 'vue'
import { api } from '../services/api'

const links = ref([])
const activeTags = ref(new Set())
const allTags = ref([])
const loading = ref(true)
const error = ref(null)

const loadLinks = async () => {
  try {
    loading.value = true
    const response = await api.getAllLinks()
    links.value = response.data
    updateTags(response.data)
  } catch (err) {
    error.value = 'Error loading links'
    console.error('Error loading links:', err)
  } finally {
    loading.value = false
  }
}

const updateTags = (links) => {
  const tagSet = new Set()
  links.forEach((link) => {
    if (link.tags) {
      link.tags.forEach((tag) => tagSet.add(tag))
    }
  })
  allTags.value = Array.from(tagSet).sort()
}

const toggleTag = (tag) => {
  if (activeTags.value.has(tag)) {
    activeTags.value.delete(tag)
  } else {
    activeTags.value.add(tag)
  }
}

const clearTags = () => {
  activeTags.value.clear()
}

const filteredLinks = computed(() => {
  if (activeTags.value.size === 0) return links.value
  return links.value.filter(
    (link) => link.tags && Array.from(activeTags.value).every((tag) => link.tags.includes(tag)),
  )
})

const deleteLink = async (id) => {
  if (!confirm('Are you sure you want to delete this link?')) return

  try {
    await api.deleteLink(id)
    await loadLinks()
  } catch (err) {
    console.error('Error deleting link:', err)
    alert('Error deleting link')
  }
}

onMounted(() => {
  loadLinks()
})
</script>
