// frontend-angular/src/app/components/link-detail/link-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule, ActivatedRoute } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { Link, Comment } from '../../models/link.interface';

@Component({
  selector: 'app-link-detail',
  templateUrl: './link-detail.component.html',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
})
export class LinkDetailComponent implements OnInit {
  link: Link | null = null;
  comments: Comment[] = [];
  newComment = '';
  loading = true;
  error: string | null = null;

  constructor(private route: ActivatedRoute, private api: ApiService) {}

  ngOnInit() {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.loadLinkAndComments(id);
    }
  }

  async loadLinkAndComments(id: string) {
    try {
      this.loading = true;
      const [linkResponse, commentsResponse] = await Promise.all([
        this.api.getLink(id),
        this.api.getComments(id),
      ]);
      this.link = linkResponse.data;
      this.comments = commentsResponse.data;
    } catch (err) {
      this.error = 'Error loading link details';
      console.error('Error:', err);
    } finally {
      this.loading = false;
    }
  }

  async handleVote(value: number) {
    if (!this.link) return;

    try {
      const response = await this.api.voteLink(this.link._id, value);
      this.link = response.data;
    } catch (err) {
      console.error('Error voting:', err);
      alert('Error voting');
    }
  }

  async handleCommentSubmit() {
    if (!this.link || !this.newComment.trim()) return;

    try {
      await this.api.createComment({
        linkId: this.link._id,
        content: this.newComment,
      });
      this.newComment = '';
      const commentsResponse = await this.api.getComments(this.link._id);
      this.comments = commentsResponse.data;
    } catch (err) {
      console.error('Error posting comment:', err);
      alert('Error posting comment');
    }
  }
}

<div class="container">
  <div class="text-center mb-20">
    <a routerLink="/">
      <button>Back to List</button>
    </a>
  </div>

  <ng-container *ngIf="loading">
    <div class="loading">Loading...</div>
  </ng-container>

  <ng-container *ngIf="error">
    <div class="error">{{ error }}</div>
  </ng-container>

  <ng-container *ngIf="!loading && !error && link">
    <div class="link-card">
      <h2>{{ link.title }}</h2>
      <p>
        <a [href]="link.url" target="_blank" rel="noopener noreferrer">
          {{ link.url }}
        </a>
      </p>
      <p class="description">{{ link.description }}</p>
      <div class="tags">
        <span *ngFor="let tag of link.tags" class="tag-filter">
          {{ tag }}
        </span>
      </div>
    </div>

    <div class="votes">
      <h3>Votes: {{ link.votes }}</h3>
      <div class="vote-buttons">
        <button (click)="handleVote(1)">👍 Upvote</button>
        <button class="delete" (click)="handleVote(-1)">👎 Downvote</button>
      </div>
    </div>

    <div class="comments">
      <h3>Comments</h3>
      <form (ngSubmit)="handleCommentSubmit()" class="comment-form">
        <div class="form-group">
          <textarea
            [(ngModel)]="newComment"
            name="comment"
            rows="4"
            placeholder="Write your comment here..."
            required
          ></textarea>
        </div>
        <div class="text-center">
          <button type="submit">Add Comment</button>
        </div>
      </form>

      <div class="comments-list mt-20">
        <div *ngFor="let comment of comments" class="comment">
          <p>{{ comment.content }}</p>
          <small>{{ comment.createdAt | date : "medium" }}</small>
        </div>
      </div>
    </div>
  </ng-container>
</div>

// frontend-vue/src/views/LinkDetail.vue
<template>
  <div class="container">
    <div class="text-center mb-20">
      <router-link to="/">
        <button>Back to List</button>
      </router-link>
    </div>

    <div v-if="loading" class="loading">Loading...</div>
    <div v-else-if="error" class="error">{{ error }}</div>
    <template v-else-if="link">
      <div class="link-card">
        <h2>{{ link.title }}</h2>
        <p>
          <a :href="link.url" target="_blank">{{ link.url }}</a>
        </p>
        <p class="description">{{ link.description }}</p>
        <div class="tags">
          <span v-for="tag in link.tags" :key="tag" class="tag-filter">
            {{ tag }}
          </span>
        </div>
      </div>

      <div class="votes">
        <h3>Votes: {{ link.votes }}</h3>
        <div class="vote-buttons">
          <button @click="handleVote(1)">👍 Upvote</button>
          <button class="delete" @click="handleVote(-1)">👎 Downvote</button>
        </div>
      </div>

      <div class="comments">
        <h3>Comments</h3>
        <form @submit.prevent="handleCommentSubmit" class="comment-form">
          <div class="form-group">
            <textarea
              v-model="newComment"
              rows="4"
              placeholder="Write your comment here..."
              required
            ></textarea>
          </div>
          <div class="text-center">
            <button type="submit">Add Comment</button>
          </div>
        </form>

        <div class="comments-list mt-20">
          <div v-for="comment in comments" :key="comment._id" class="comment">
            <p>{{ comment.content }}</p>
            <small>{{ new Date(comment.createdAt).toLocaleString() }}</small>
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { api } from '../services/api'

const route = useRoute()
const link = ref(null)
const comments = ref([])
const newComment = ref('')
const loading = ref(true)
const error = ref(null)

const loadLinkAndComments = async () => {
  try {
    loading.value = true
    const [linkResponse, commentsResponse] = await Promise.all([
      api.getLink(route.params.id),
      api.getComments(route.params.id),
    ])
    link.value = linkResponse.data
    comments.value = commentsResponse.data
  } catch (err) {
    error.value = 'Error loading link details'
    console.error('Error:', err)
  } finally {
    loading.value = false
  }
}

const handleVote = async (value) => {
  try {
    const response = await api.voteLink(route.params.id, value)
    link.value = response.data
  } catch (err) {
    console.error('Error voting:', err)
    alert('Error voting')
  }
}

const handleCommentSubmit = async () => {
  if (!newComment.value.trim()) return

  try {
    await api.createComment({
      linkId: route.params.id,
      content: newComment.value,
    })
    newComment.value = ''
    const commentsResponse = await api.getComments(route.params.id)
    comments.value = commentsResponse.data
  } catch (err) {
    console.error('Error posting comment:', err)
    alert('Error posting comment')
  }
}

onMounted(() => {
  loadLinkAndComments()
})
</script>
